import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import React from "react";
import Image from "next/image";
import background from "/public/background.png";
import "tw-elements-react/dist/css/tw-elements-react.min.css";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
      {/*Background*/}
      <div className={'flex flex-col items-center justify-between'}>
          <div className={'relative w-full'}>
              <div className={'fixed object-cover blur-sm -z-10'}>
                  <Image
                      src={background}
                      alt={'Picture of background'}
                      priority={true}
                      placeholder={'blur'}
                  />
              </div>
          </div>
          {children}
      </div>
      </body>
    </html>
  )
}
